spring:
  datasource:
    url: jdbc:h2:mem:mck-career-tool
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: false


  h2:
    console:
      enabled: true
      path: /h2-console

security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:career-tool}
      client-secret: ${CLIENT_SECRET:career-tool}

jwt:
  secret: ${JWT_SECRET:career-tool}
  duration: ${JWT_DURATION:3600}



