spring:
  datasource:
    url: jdbc:h2:mem:mck-career-tool
    username: sa
    password:
  jpa:
    show-sql: true
    open-in-view: false


  h2:
    console:
      enabled: true
      path: /h2-console




