spring:
  profiles:
    active: ${APP_PROFILE:test}
    
  jpa:
    open-in-view: false

security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:career-tool}
      client-secret: ${CLIENT_SECRET:career-tool}

jwt:
  secret: ${JWT_SECRET:career-tool}
  duration: ${JWT_DURATION:3600}



