spring:
  datasource:
    url: jdbc:h2:mem:mck-career-tool
    username: sa
    password:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.example.com/issuer

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false

